In [ ]:
transition_tuple = namedtuple('Transition', ('s', 'a', 'r', 'new_s'))
    #transition_tuple = np.full((4), np.NaN)

In [ ]:
    #(s, a, r, s') is initialized above
    self.transitions = deque(maxlen=TRANSITION_HISTORY_SIZE)

    #(epsilon, alpha, gamma) is initialized above
    self.hyper_params = np.array([epsilon,alpha,gamma])

In [2]:
import os
import pickle
import random

import numpy as np

In [49]:
weights = np.random.rand(3,6)

In [56]:
weights

array([[0.38790886, 0.4394208 , 0.45106321, 0.23837173, 0.64446096,
        0.71908456],
       [0.86835158, 0.65182871, 0.94595353, 0.33834209, 0.72070478,
        0.03345976],
       [0.83190102, 0.11772551, 0.53019775, 0.40359731, 0.80705507,
        0.8600288 ]])

In [63]:
weights * (1/np.sum(weights, axis=1))[:, np.newaxis]

array([[0.13467608, 0.15256024, 0.15660231, 0.08275905, 0.22374707,
        0.24965526],
       [0.24401217, 0.1831679 , 0.2658188 , 0.09507622, 0.2025225 ,
        0.0094024 ],
       [0.23430495, 0.0331574 , 0.14933022, 0.1136732 , 0.22730709,
        0.24222714]])

In [61]:
np.matmul(1/np.linalg.norm(weights, axis=1), weights)

array([1.36246196, 0.82442986, 1.27129414, 0.65108912, 1.46415269,
       1.14002443])

In [51]:
state_to_features = np.array([1,2,3])

In [52]:
a = np.matmul(state_to_features,weights)
a

array([4.62031507, 2.09625477, 3.93356353, 2.12584782, 4.50703571,
       3.36609047])

In [54]:
a = np.matmul(state_to_features,weights[:,0])

a

4.620315068124965

In [16]:
a.argmax(axis=0)

1

In [21]:
a = np.array([[1,1],[2,2],[2,5],[1,3]])

b = np.array([2,2])

In [37]:
np.sqrt((a[:,0]-b[0])**2 + (a[:,1]-b[1])**2).argmin()

1

In [27]:
np.linalg.norm(a-b)

3.605551275463989

In [ ]:
game_state["coins"]
    game_state["self"][3]

    index_nearest_coin = np.sqrt((game_state["coins"][:,0]-game_state["self"][3][0])**2 + (game_state["coins"][:,1]-game_state["self"][3][1])**2).argmin()


In [40]:


# For example, you could construct several channels of equal shape, ...
channels = []
channels.append(np.zeros(6))
channels.append(np.zeros(6))
# concatenate them as a feature tensor (they must have the same shape), ...
stacked_channels = np.stack(channels)
# and return them as a vector
stacked_channels.reshape(-1)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
from collections import namedtuple, deque

In [46]:
TRANSITION_HISTORY_SIZE = 3
d = deque(np.full((TRANSITION_HISTORY_SIZE), None), maxlen=TRANSITION_HISTORY_SIZE)

d.append(1)
d.append(2)
d

deque([1, 2])

In [48]:
TRANSITION_HISTORY_SIZE = 3
d = deque(maxlen=TRANSITION_HISTORY_SIZE)

d.append(1)
d.append(2)
d.append(3)
d.append(4)

d

deque([2, 3, 4])

In [55]:
os.path.isfile("my-saved-model.pt")

True

In [189]:
self_coord = np.array([4,4])
self_coord_new = np.array([3,4])

bombs_coord = np.array([[4,0],[4,1],[4,2],[4,3],[4,4],[0,3],[1,3],[2,3],[3,3],[3,4]])

In [193]:
bombs_coord[0][1]

0

In [165]:
bombs_coord[( (bombs_coord[:,0] == self_coord[0]) & ((bombs_coord[:,1] >= self_coord[1] - 3) | (bombs_coord[:,1] <= self_coord[1] + 3))  ) | ( (bombs_coord[:,1] == self_coord[1]) & ((bombs_coord[:,0] >= self_coord[0] - 3) | (bombs_coord[:,0] <= self_coord[0] + 3)) )]

array([[4, 0],
       [4, 1],
       [4, 2],
       [4, 3],
       [4, 4],
       [3, 4]])

In [166]:
bombs_in_range = bombs_coord[( (bombs_coord[:,0] == self_coord[0]) & ((bombs_coord[:,1] >= self_coord[1] - 3) | (bombs_coord[:,1] <= self_coord[1] + 3))  ) | ( (bombs_coord[:,1] == self_coord[1]) & ((bombs_coord[:,0] >= self_coord[0] - 3) | (bombs_coord[:,0] <= self_coord[0] + 3)) )]

False

In [147]:
a = np.nonzero(self_coord_new - self_coord)
b = np.where((self_coord_new - self_coord) == 0)[0][0]
a = a[0][0]

bombs_in_range[:,b]

array([4, 4, 4, 4, 4, 3])

In [74]:
def get_bombs_in_range(self_coord,bombs_coord):
    return bombs_coord[( (bombs_coord[:,0] == self_coord[0]) & ((bombs_coord[:,1] >= self_coord[1] - 3) | (bombs_coord[:,1] <= self_coord[1] + 3))  ) | ( (bombs_coord[:,1] == self_coord[1]) & ((bombs_coord[:,0] >= self_coord[0] - 3) | (bombs_coord[:,0] <= self_coord[0] + 3)) )]

In [ ]:
def goes_away_from_bomb(self_coord, bombs_in_range, self_coord_new):
    
    if bombs_in_range.size == 0:
        return False, 0

    else:
        #coord that changed
        a = np.nonzero(self_coord_new - self_coord)[0][0]
        #coord that didnt change
        b = np.where((self_coord_new - self_coord) == 0)[0][0]


        #weighted score of number of moved away bombs
        num = 0


        #get points for moving out of range (moved orthogonally to bomb)
        num += np.count_nonzero(bombs_in_range[:,b] != self_coord[a])

        #moved parallel to bomb

        #remaining bombs
        remaining_bombs = bombs_in_range[bombs_in_range[:,b] == self_coord[b]]

        #give reward for moving away from bombs
        num += 1 * ((abs(remaining_bombs[:,a] - self_coord_new[a]) - abs(remaining_bombs[:,a] - self_coord[a])) == 1).sum()

        #give penalty for moving towards ... number of bombs
        num -= 5 * ((abs(remaining_bombs[:,a] - self_coord_new[a]) - abs(remaining_bombs[:,a] - self_coord[a])) == -1).sum()

        return True, num

    


In [ ]:
game_state["bombs"][0][0] - game_state["self"][3]

In [195]:
game_state_bombs_00 = np.array([4,4])
game_state_self = np.array([3,4])


game_state_bombs_00 - game_state_self

array([1, 0])

In [ ]:
np.sqrt((game_state["coins"][:,0]-game_state["self"][3][0])**2 + (game_state["coins"][:,1]-game_state["self"][3][1])**2).argmin()